version: '3'
services:
  rtsp_server:
    build: .
    image: rtsp_server:2.1
    ports:
      - 8053:8080
    environment:
      - RTSP_STREAM_CORS_ENABLED=true
      - RTSP_STREAM_DEBUG=false
      - RTSP_STREAM_AUDIO_ENABLED=false
    volumes:
      - ./logs:/var/log/rtsp-stream
      - ./videos:/app/videos
volumes:
  logs:
  videos:
